### ISSUE TITLE
Issues with Chrome/Firefox in Production (Heroku)

### ISSUE THREAD

**Issue by johncjensen** [leonid-shevtsov/unobtrusive_flash#16]
I'm working on an application using unobtrusive_flash and have ran into some snags when deployed. At first I thought it was issues with Turbolinks but isn't appearing to be the case. 

I have created a new rails 4.1.1 application and deployed it to show the example of how the flash/notices aren't showing up when using Chrome/Firefox (latest versions).

repo & deployed app 
https://github.com/johncjensen/unobtrusive-flash-testing
http://unobtrusive-flash-testing.herokuapp.com

When using the console to trigger it with following it appears:
`UnobtrusiveFlash.showFlashMessage('Error', {type: 'error', timeout: 0})`

Attached are two screenshots of chrome & firefox displaying with the console trigger
![chrome-unobtrusive-flash-testing 2](https://cloud.githubusercontent.com/assets/2812203/3100695/c54e88d2-e61f-11e3-8bb9-50911af295fd.png)
![firefox-unobtrusive-flash-testing](https://cloud.githubusercontent.com/assets/2812203/3100697/cc0970f6-e61f-11e3-9fcf-be4e10221c85.png)

**Comment by jessewmc** [comment]
Just a note for anyone who arrives here from Google as I did.

I was having the same issue, but with amazon elasticbeanstalk.com. Unobtrusive flash wasn't working in production and eventually I found this issue.

You can fix it by overriding unobtrusive_flash_domain as seen https://github.com/leonid-shevtsov/unobtrusive_flash/blob/master/lib/unobtrusive_flash/controller_mixin.rb here, in your application controller. Just add the shared domain (in my case elasticbeanstalk.com) to the regex in the same manner as the current heroku workaround.

**Comment by projectnoa** [comment]
This solution should be in Stackoverflow or something because it might be hard to find for other people.

Just in case, i will put some keywords I used to find this answer so google index this page.

Rails unobtrusive_flash not working in production Amazon ElasticBeanstalk EB
