### ISSUE TITLE
Former flash messages reappear when a new one is displayed

### ISSUE THREAD

**Issue by xpothrat** [leonid-shevtsov/unobtrusive_flash#23]
I just set up unobtrusive_flash gem in my Rails 4 App.
I am using V3.1.0 of the gem with bootstrap pack.

If i don't manually delete flash message by clicking on the cross or if i don't refresh the page, the flash messages are not destroyed and are redisplayed with the new ones. redirecting doesn't seem to destroy flash message. neither flashOptions['timeout']. It just make them disappaer until the next new flash message is displayed.
So when a new flash message is dispalyed, instead of having just the new one, i have also all former ones (except the ones i have manually deleted) since the last refresh

Thanks for your help

**Comment by pruchai** [comment]
You can try using 

```ruby
flash.now[:notice] = 'This is my notice'
```

If that does not work, try this
https://github.com/pruchai/unobtrusive_flash/commit/9d70621ce665e99b13517b4e7ebbe5ddebcab822

**Comment by ZuzannaSt** [comment]
flash.now[:notice] didn't work for me. @pruchai which line in that commit should help?

**Comment by mkaplan9** [comment]
see the pavelgnom fork. it fixed it for me.

**Comment by leonid-shevtsov** [comment]
@mkaplan9 thanks for noticing! I'll pull that fix asap. (cc @pavelgnom)

**Comment by leonid-shevtsov** [comment]
Closing this as it was in fact pulled and released in v3.1.1
