### ISSUE TITLE
Preventing alert from displaying within the body

### ISSUE THREAD

**Issue by twicebishop** [leonid-shevtsov/unobtrusive_flash#25]
I'm attempting "Option 3: Roll your own" by binding a jGrowl to the flash handler.
It works except for now I get a flash message appearing in the body along with the jGrowl popup.
I was able to workaround this by declaring a .unobtrusive-flash-container element on the page and adding "visibility: hidden" to it's css.
Is there a easier way to prevent unobtrusive flash from falling back to the body element?

**Comment by leonid-shevtsov** [comment]
You are requiring `unobtrusive-flash-ui.js`, and you only need `unobtrusive-flash.js`, the non-visual part. You should include just the latter, and write the UI part specifically for jGrowl.

Also, I'd appreciate a jGrowl PR very much. :)
