### ISSUE TITLE
Devise and devise_error_messages!

### ISSUE THREAD

**Issue by fist28** [leonid-shevtsov/unobtrusive_flash#26]
I would like to use unobtrusive_flash gem but Devise use `resource.errors` to storage form messages.
I see problem with `RegistrationsController` and action `new`/`create`. Do you have any way to use `unobtrusive_flash` with Devise `RegistrationsController`?

I try use solutions from http://stackoverflow.com/questions/4101641/rails-devise-handling-devise-error-messages but my cookie with notice has empy value.

**Comment by go2point-ru** [comment]
+1

**Comment by mibamur** [comment]
+1
how?

**Comment by leonid-shevtsov** [comment]
I think if you just write the errors into `flash.now` it will work. Didn't test that though.
