### ISSUE TITLE
Getting deprecate .load() in unobtrusive_flash.js

### ISSUE THREAD

**Issue by swachtma** [leonid-shevtsov/unobtrusive_flash#36]
I'm trying to install the latest 3.2 version of this gem.  But the Javascript file I end up with is using the deprecated .load() function from jQuery rather than the .on('load') alternative.

What's odd is that the function my gem has locally in it's unobtrusive_flash.js file contradicts what I see in the latest repo. 

I have:
`
// We want to remove cookies from the flash as soon as possible, but we only want to show then after all the scripts have loaded,
  // including any flash handlers
  var pageCookies = extractFlashFromCookies();
  $(window).load(function() {
    UnobtrusiveFlash.showFlash(pageCookies);
  });
`

But in the repo I see:
'
  // We want to remove cookies from the flash as soon as possible, but we only want to show then after all the scripts have loaded,
  // including any flash handlers
  var pageCookies = extractFlashFromCookies();
  $(window).on('load', function() {
    UnobtrusiveFlash.showFlash(pageCookies);
  });
'

Is this something I'm doing wrong, or is the gem out of date?

I'm running Rails 5.0.0, and jQuery 3.1.0

**Comment by leonid-shevtsov** [comment]
Please use version 3.3.0 that fixes this issue and is fully compatible with both Rails 5 and jQuery 3.
