### ISSUE TITLE
Not a good practice to put request data directly into page

### ISSUE THREAD

**Issue by bf4** [leonid-shevtsov/unobtrusive_flash#38]
Then you're relying on implicit xss protection in Rails

**Comment by leonid-shevtsov** [comment]
Please elaborate where this is happening.

**Comment by bf4** [comment]
You win, was reading on my phone, and missed `html_safe_value = value.html_safe? ? value : ERB::Util.html_escape(value)`

So, I'll say sorry for the unnecessary issue :(
