### ISSUE TITLE
NoMethodError: undefined method `+' for nil:NilClass, in controller_mixin.rb, line 59

### ISSUE THREAD

**Issue by fredngo** [leonid-shevtsov/unobtrusive_flash#43]
I'm sometimes experiencing the following:

```
NoMethodError: undefined method `+' for nil:NilClass
"/app/vendor/bundle/ruby/2.4.0/gems/unobtrusive_flash-3.3.1/lib/unobtrusive_flash/controller_mixin.rb" line 59 in append_flash_to_cookie
"/app/vendor/bundle/ruby/2.4.0/gems/unobtrusive_flash-3.3.1/lib/unobtrusive_flash/controller_mixin.rb" line 11 in prepare_unobtrusive_flash
```

Any idea why `cookie_flash` would be `nil` at this line? https://github.com/leonid-shevtsov/unobtrusive_flash/blob/master/lib/unobtrusive_flash/controller_mixin.rb#L59

**Comment by leonid-shevtsov** [comment]
Hi, thanks for reporting this, looks like sometimes `null` arrives as the cookie string from the client, and it's parsed into `nil`. I added special handling for this situation. 

Can you link this issue to a particular browser, maybe?

**Comment by fredngo** [comment]
It looks like mostly Chrome and Firefox on both Windows and Mac...

<img width="478" alt="screen shot 2017-06-21 at 7 19 08 am" src="https://user-images.githubusercontent.com/11791/27388992-fe1c0158-5651-11e7-8c6a-1b31a56193a2.png">

I did replace https://github.com/pboling/cacheable-flash with unobtrusive_flash on that day, so maybe somehow the old flash cookies were not compatible?
